[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'numpy']

[project]
name = 'f2py_examples'
version = '0.0.1'
requires-python = ">=3.10"
description = 'Example package using the meson-python build backend & fortran'
