on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Wheel, ${{ matrix.buildplat[0] }}:python-${{ matrix.python[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: true
      matrix:
        buildplat:
          # should also be able to do multi-archs on a single entry, e.g.
          # [windows-2019, win*, "AMD64 x86"]. However, those two require a different compiler setup
          # so easier to separate out here.
          - [ubuntu-22.04, manylinux, x86_64, "", ""]
          - [macos-13, macosx, x86_64, openblas, "10.14"]
          - [windows-2019, win, AMD64, "", ""]
        python: [["cp311", "3.11"]]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: 3.11

      - name: win_amd64 - install rtools (match scipy version)
        run: |
          # mingw-w64
          choco install rtools -y --no-progress --force --version=4.0.0.20220206
          echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH
        if: ${{ runner.os == 'Windows' }}

      - name: windows - set PKG_CONFIG_PATH
        if: ${{ runner.os == 'Windows' }}
        run: |
          $env:CIBW = "${{ github.workspace }}"
          # It seems somewhere in the env passing, `\` is not
          # passed through, so convert it to '/'
          $env:CIBW=$env:CIBW.replace("\","/")
          echo "CIBW_ENVIRONMENT=PKG_CONFIG_PATH=$env:CIBW" >> $env:GITHUB_ENV

      - name: Setup macOS
        if: startsWith( matrix.buildplat[0], 'macos-' )
        run: |
          if [[ ${{ matrix.buildplat[3] }} == 'accelerate' ]]; then
            echo CIBW_CONFIG_SETTINGS=\"setup-args=-Dblas=accelerate\" >> "$GITHUB_ENV"
            # Always use preinstalled gfortran for Accelerate builds
            ln -s $(which gfortran-13) gfortran
            export PATH=$PWD:$PATH
            echo "PATH=$PATH" >> "$GITHUB_ENV"
            LIB_PATH=$(dirname $(gfortran --print-file-name libgfortran.dylib))
          fi
          if [[ ${{ matrix.buildplat[4] }} == '10.13' ]]; then
            # 20241017 macos-13 images span Xcode 14.1-->15.2
            XCODE_VER='14.1'
          else
            XCODE_VER='15.2'
          fi
          CIBW="sudo xcode-select -s /Applications/Xcode_${XCODE_VER}.app"
          echo "CIBW_BEFORE_ALL=$CIBW" >> $GITHUB_ENV
          # setting SDKROOT necessary when using the gfortran compiler
          # installed in cibw_before_build_macos.sh
          sudo xcode-select -s /Applications/Xcode_${XCODE_VER}.app
          CIBW="MACOSX_DEPLOYMENT_TARGET=${{ matrix.buildplat[4] }}\
            SDKROOT=$(xcrun --sdk macosx --show-sdk-path)\
            PKG_CONFIG_PATH=${{ github.workspace }}"
          echo "CIBW_ENVIRONMENT=$CIBW" >> "$GITHUB_ENV"

          echo "REPAIR_PATH=$LIB_PATH" >> "$GITHUB_ENV"

          PREFIX=DYLD_LIBRARY_PATH="\$(dirname \$(gfortran --print-file-name libgfortran.dylib))"
          # remove libgfortran from location used for linking (if any), to
          # check wheel has bundled things correctly and all tests pass without
          # needing installed gfortran
          POSTFIX=" sudo rm -rf /opt/gfortran-darwin-x86_64-native &&\
                    sudo rm -rf /usr/local/gfortran/lib"
          CIBW="$PREFIX delocate-listdeps -d {wheel} && echo "-----------" &&\
            $PREFIX delocate-wheel -v $EXCLUDE --require-archs \
            {delocate_archs} -w {dest_dir} {wheel} && echo "-----------" &&\
            delocate-listdeps -d {dest_dir}/*.whl && echo "-----------" &&\
            $POSTFIX"

          # Rename x86 Accelerate wheel to test on macOS 13 runner
          if [[ ${{ matrix.buildplat[0] }} == 'macos-13' && ${{ matrix.buildplat[4] }} == '14.0' ]]; then
            CIBW+=" && mv {dest_dir}/\$(basename {wheel}) \
              {dest_dir}/\$(echo \$(basename {wheel}) | sed 's/14_0/13_0/')"
          fi

          # macos-arm64-openblas wheels that target macos-12 need a
          # MACOS_DEPLOYMENT_TARGET of 12.3 otherwise delocate complains.
          # Unclear of cause, possibly build tool related.
          # This results in wheels that have 12_3 in their name. Since Python
          # has no concept of minor OS versions in packaging land rename the
          # wheel back to 12.
          if [[ ${{ matrix.buildplat[0] }} == 'macos-14' && ${{ matrix.buildplat[4] }} == '12.3' ]]; then
            CIBW+=" && echo \$(ls {dest_dir}) && \
            mv {dest_dir}/*.whl \$(find {dest_dir} -type f -name '*.whl' | sed 's/12_3/12_0/')"
          fi
          echo "CIBW_REPAIR_WHEEL_COMMAND_MACOS=$CIBW" >> "$GITHUB_ENV"

      - name: Build wheels
        uses: pypa/cibuildwheel@7940a4c0e76eb2030e473a5f864f291f63ee879b # v2.21.3
        env:
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}*
          CIBW_ARCHS: ${{ matrix.buildplat[2] }}

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          path: ./wheelhouse/*.whl
          name: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
            ${{ matrix.buildplat[2] }} ${{ matrix.buildplat[3] }}
            ${{ matrix.buildplat[4] }}
