on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Wheel, ${{ matrix.buildplat[0] }}:python-${{ matrix.python[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: true
      matrix:
        buildplat:
          # should also be able to do multi-archs on a single entry, e.g.
          # [windows-2019, win*, "AMD64 x86"]. However, those two require a different compiler setup
          # so easier to separate out here.
          # - [ubuntu-22.04, manylinux, x86_64, "", ""]
          # - [macos-13, macosx, x86_64, openblas, "10.14"]
          - [windows-2019, environment-win.yml]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: ${{ matrix.buildplat[1] }}
          conda-remove-defaults: true
          channels: conda-forge
          activate-environment: playground-mesonbuild-dev

      - name: Build f2py_examples
        run: |
          pip install .
