on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Conda, ${{ matrix.buildplat[0] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: true
      matrix:
        buildplat:
          # should also be able to do multi-archs on a single entry, e.g.
          # [windows-2019, win*, "AMD64 x86"]. However, those two require a different compiler setup
          # so easier to separate out here.
          - [ubuntu-22.04, conda/environment-linux.yml, "bash -el {0}"]
          - [macos-13, conda/environment-macos.yml, "bash -el {0}"]
          - [windows-2019, environment-win.yml, "cmd {0}"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: ${{ matrix.buildplat[1] }}
          conda-remove-defaults: true
          channels: conda-forge
          activate-environment: playground-mesonbuild-dev

      - name: Build f2py_examples
        shell: ${{ buildplat[2] }}}
        run: |
          meson setup builddir
          meson compile -C builddir
